import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiTailwindcss,
  SiTypescript,
  SiJavascript,
  SiRedux,
  SiGraphql,
  SiDocker,
  // SiAmazon,
  SiFirebase,
  SiPrisma,
  SiPython,
  SiDjango,
  SiFlask,
  SiVuedotjs,
  SiAngular,
  SiGit,
  SiFigma,
  SiStripe,
  SiSocketdotio,
  SiSupabase,
  SiVercel,
  SiRedis,
  SiSqlite,
} from "react-icons/si";

export const TECH_ICONS: Record<string, { Icon: IconType; color: string }> = {
  React: { Icon: SiReact, color: "#61DAFB" },
  "Next.js": { Icon: SiNextdotjs, color: "#FFFFFF" },
  "Node.js": { Icon: SiNodedotjs, color: "#5FA04E" },
  Express: { Icon: SiExpress, color: "#FFFFFF" },
  MongoDB: { Icon: SiMongodb, color: "#47A248" },
  PostgreSQL: { Icon: SiPostgresql, color: "#4169E1" },
  MySQL: { Icon: SiMysql, color: "#4479A1" },
  "Tailwind CSS": { Icon: SiTailwindcss, color: "#38BDF8" },
  Tailwind: { Icon: SiTailwindcss, color: "#38BDF8" },
  TypeScript: { Icon: SiTypescript, color: "#3178C6" },
  JavaScript: { Icon: SiJavascript, color: "#F7DF1E" },
  Redux: { Icon: SiRedux, color: "#764ABC" },
  GraphQL: { Icon: SiGraphql, color: "#E10098" },
  Docker: { Icon: SiDocker, color: "#2496ED" },
  // AWS: { Icon: SiAmazon, color: "#FF9900" },
  Firebase: { Icon: SiFirebase, color: "#FFCA28" },
  Prisma: { Icon: SiPrisma, color: "#FFFFFF" },
  Python: { Icon: SiPython, color: "#3776AB" },
  Django: { Icon: SiDjango, color: "#0C4B33" },
  Flask: { Icon: SiFlask, color: "#FFFFFF" },
  "Vue.js": { Icon: SiVuedotjs, color: "#4FC08D" },
  Angular: { Icon: SiAngular, color: "#DD0031" },
  Git: { Icon: SiGit, color: "#F05032" },
  Figma: { Icon: SiFigma, color: "#F24E1E" },
  Stripe: { Icon: SiStripe, color: "#635BFF" },
  "Socket.io": { Icon: SiSocketdotio, color: "#FFFFFF" },
  Supabase: { Icon: SiSupabase, color: "#3ECF8E" },
  Vercel: { Icon: SiVercel, color: "#FFFFFF" },
  Redis: { Icon: SiRedis, color: "#DC382D" },
  SQLite: { Icon: SiSqlite, color: "#003B57" },
};
